apiVersion: v1
kind: Service
metadata:
  name: twelve-clouds-service
  labels:
    app: twelve-clouds
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: twelve-clouds