apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ssd
  labels:
    app: storage-app
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
